name: Auto Update Version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies
      - name: Set Up Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Step 3: Run the update script (passing the GH_TOKEN as an environment variable)
      - name: Run Update Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass the GH_TOKEN to the script
        run: |
          chmod +x update-version.sh
          ./update-version.sh
          
      # Step 4: Trigger builder workflow
      - name: Trigger Builder Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "autoupdate", "client_payload": {}}'
