name: Auto Update Version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies
      - name: Set Up Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Step 3: Configure Git with PAT
      - name: Configure Git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

      # Step 4: Run the update script
      - name: Run Update Script
        run: |
          chmod +x update-version.sh
          ./update-version.sh
